const fs = require('fs');
const file = 'src/components/LancamentosRelatoriosModule.tsx';
let code = fs.readFileSync(file, 'utf8');

const regexIterface = /interface KitLancamento \{[\s\S]*?\n\}/;
const newInterface = `interface KitLancamento {
  id: string;
  bloco: string;
  apto: string;
  pavimento: string;
  coluna: string;
  comodo: string;
  tipologia: string;
  folhaLargura: string;
  folhaAltura: string;
  qtdeFolhasPorKit: string;
  acabamentoPorta: string;
  caracteristicaPorta: string;
  abertura: string;
  aduelaLargura: string;
  aduelaAltura: string;
  regulagem: string;
  acabamentoAduela: string;
  fechaduraMarca: string;
  fechaduraGrid: string;
  fechaduraTipo: string;
  dobradicaMarca: string;
  dobradicaMedida: string;
  qtdeLadosAduela: string;
  montantesMedida: string;
  montantesFolgas: string;
  bitsQtde: string;
  bitsFaces: string;
  camarao: boolean;
  correr: boolean;
  pivotante: boolean;
  veneziana: boolean;
  grelha: boolean;
  bandeira: boolean;
  chapa: boolean;
  vidro: boolean;
  fechaFresta: boolean;
  kitDuplo: boolean;
  observacao: string;
}`;
code = code.replace(regexIterface, newInterface);

const regexInitialForm = /const INITIAL_FORM: Omit<KitLancamento, 'id'> = \{[\s\S]*?\n\};/;
const newInitialForm = `const INITIAL_FORM: Omit<KitLancamento, 'id'> = {
  bloco: '', apto: '', pavimento: '', coluna: '', comodo: '', tipologia: '',
  folhaLargura: '', folhaAltura: '', qtdeFolhasPorKit: '',
  acabamentoPorta: '', caracteristicaPorta: '', abertura: '',
  aduelaLargura: '', aduelaAltura: '', regulagem: '',
  acabamentoAduela: '', fechaduraMarca: '', fechaduraGrid: '', fechaduraTipo: '',
  dobradicaMarca: '', dobradicaMedida: '', qtdeLadosAduela: '',
  montantesMedida: '', montantesFolgas: '', bitsQtde: '', bitsFaces: '',
  camarao: false, correr: false, pivotante: false, veneziana: false, grelha: false, bandeira: false, chapa: false, vidro: false, fechaFresta: false, kitDuplo: false, observacao: ''
};`;
code = code.replace(regexInitialForm, newInitialForm);

const INITIAL_KITS = [
  {"bloco":"1","apto":"102","pavimento":"1","coluna":"2","comodo":"BANHEIRO","tipologia":"PM1F","folhaLargura":"620","folhaAltura":"2070","qtdeFolhasPorKit":"1","acabamentoPorta":"BRANCO","caracteristicaPorta":"HONEY","abertura":"ESQUERDA","aduelaLargura":"90","aduelaAltura":"2120","regulagem":"REG 50","acabamentoAduela":"PET MDF BRA+BOR+REG","fechaduraMarca":"LA FONTE","fechaduraGrid":"55","fechaduraTipo":"WC","dobradicaMarca":"LA FONTE","dobradicaMedida":"3 x 2,5","qtdeLadosAduela":"3","montantesMedida":"","montantesFolgas":"","bitsQtde":"","bitsFaces":"","camarao":false,"correr":false,"pivotante":false,"veneziana":true,"grelha":false,"bandeira":false,"chapa":false,"vidro":false,"fechaFresta":false,"kitDuplo":false,"observacao":""},
  {"bloco":"1","apto":"104","pavimento":"1","coluna":"4","comodo":"ENTRADA","tipologia":"PM3","folhaLargura":"820","folhaAltura":"2100","qtdeFolhasPorKit":"1","acabamentoPorta":"BRANCO","caracteristicaPorta":"SOLIDA","abertura":"ESQUERDA P/FORA","aduelaLargura":"170","aduelaAltura":"2110","regulagem":"REG 50","acabamentoAduela":"PET MDF BRA+BOR+REG","fechaduraMarca":"PAPAIZ","fechaduraGrid":"40","fechaduraTipo":"EXT","dobradicaMarca":"LA FONTE","dobradicaMedida":"3 x 2,5","qtdeLadosAduela":"3","montantesMedida":"","montantesFolgas":"","bitsQtde":"4","bitsFaces":"2","camarao":false,"correr":false,"pivotante":false,"veneziana":false,"grelha":false,"bandeira":false,"chapa":false,"vidro":false,"fechaFresta":true,"kitDuplo":false,"observacao":""},
  {"bloco":"1","apto":"106","pavimento":"1","coluna":"6","comodo":"QUARTO","tipologia":"PM2","folhaLargura":"720","folhaAltura":"2100","qtdeFolhasPorKit":"1","acabamentoPorta":"BRANCO","caracteristicaPorta":"HONEY","abertura":"DIREITA","aduelaLargura":"90","aduelaAltura":"2110","regulagem":"REG 70","acabamentoAduela":"PET MDF BRA+BOR+REG","fechaduraMarca":"LA FONTE","fechaduraGrid":"55","fechaduraTipo":"INT","dobradicaMarca":"LA FONTE","dobradicaMedida":"3 x 2,5","qtdeLadosAduela":"3","montantesMedida":"","montantesFolgas":"","bitsQtde":"","bitsFaces":"","camarao":false,"correr":false,"pivotante":false,"veneziana":false,"grelha":false,"bandeira":false,"chapa":false,"vidro":false,"fechaFresta":false,"kitDuplo":false,"observacao":""},
  {"bloco":"1","apto":"202","pavimento":"2","coluna":"2","comodo":"ENTRADA","tipologia":"PM3","folhaLargura":"820","folhaAltura":"2100","qtdeFolhasPorKit":"1","acabamentoPorta":"BRANCO","caracteristicaPorta":"SOLIDA","abertura":"DIREITA","aduelaLargura":"170","aduelaAltura":"2110","regulagem":"REG 70","acabamentoAduela":"PET MDF BRA+BOR+REG","fechaduraMarca":"PAPAIZ","fechaduraGrid":"40","fechaduraTipo":"EXT","dobradicaMarca":"LA FONTE","dobradicaMedida":"3 x 2,5","qtdeLadosAduela":"3","montantesMedida":"","montantesFolgas":"","bitsQtde":"4","bitsFaces":"2","camarao":false,"correr":false,"pivotante":false,"veneziana":false,"grelha":false,"bandeira":false,"chapa":false,"vidro":false,"fechaFresta":true,"kitDuplo":false,"observacao":""},
  {"bloco":"1","apto":"206","pavimento":"2","coluna":"6","comodo":"COZINHA","tipologia":"PM3F","folhaLargura":"820","folhaAltura":"2070","qtdeFolhasPorKit":"1","acabamentoPorta":"BRANCO","caracteristicaPorta":"SARRAFEADA","abertura":"DIREITA P/FORA","aduelaLargura":"150","aduelaAltura":"2120","regulagem":"REG 50","acabamentoAduela":"PET MDF BRA+BOR+REG","fechaduraMarca":"LA FONTE","fechaduraGrid":"55","fechaduraTipo":"INT","dobradicaMarca":"LA FONTE","dobradicaMedida":"3 x 2,5","qtdeLadosAduela":"3","montantesMedida":"","montantesFolgas":"","bitsQtde":"","bitsFaces":"","camarao":false,"correr":true,"pivotante":false,"veneziana":true,"grelha":true,"bandeira":false,"chapa":false,"vidro":false,"fechaFresta":false,"kitDuplo":false,"observacao":""},
  {"bloco":"1","apto":"309","pavimento":"3","coluna":"9","comodo":"COZINHA","tipologia":"PM3F","folhaLargura":"820","folhaAltura":"2070","qtdeFolhasPorKit":"1","acabamentoPorta":"BRANCO","caracteristicaPorta":"SARRAFEADA","abertura":"DIREITA","aduelaLargura":"150","aduelaAltura":"2120","regulagem":"REG 50","acabamentoAduela":"PET MDF BRA+BOR+REG","fechaduraMarca":"LA FONTE","fechaduraGrid":"55","fechaduraTipo":"INT","dobradicaMarca":"LA FONTE","dobradicaMedida":"3 x 2,5","qtdeLadosAduela":"3","montantesMedida":"","montantesFolgas":"","bitsQtde":"","bitsFaces":"","camarao":false,"correr":true,"pivotante":false,"veneziana":false,"grelha":false,"bandeira":false,"chapa":false,"vidro":true,"fechaFresta":false,"kitDuplo":false,"observacao":""},
  {"bloco":"1","apto":"509","pavimento":"5","coluna":"9","comodo":"COZINHA","tipologia":"PM3F","folhaLargura":"820","folhaAltura":"2070","qtdeFolhasPorKit":"1","acabamentoPorta":"BRANCO","caracteristicaPorta":"SARRAFEADA","abertura":"ESQUERDA","aduelaLargura":"150","aduelaAltura":"2120","regulagem":"REG 50","acabamentoAduela":"PET MDF BRA+BOR+REG","fechaduraMarca":"LA FONTE","fechaduraGrid":"55","fechaduraTipo":"INT","dobradicaMarca":"LA FONTE","dobradicaMedida":"3 x 2,5","qtdeLadosAduela":"3","montantesMedida":"","montantesFolgas":"","bitsQtde":"","bitsFaces":"","camarao":false,"correr":false,"pivotante":false,"veneziana":false,"grelha":false,"bandeira":false,"chapa":false,"vidro":true,"fechaFresta":false,"kitDuplo":false,"observacao":""},
  {"bloco":"1","apto":"709","pavimento":"7","coluna":"9","comodo":"COZINHA","tipologia":"PM3F","folhaLargura":"820","folhaAltura":"2070","qtdeFolhasPorKit":"1","acabamentoPorta":"BRANCO","caracteristicaPorta":"SARRAFEADA","abertura":"ESQUERDA","aduelaLargura":"150","aduelaAltura":"2120","regulagem":"REG 50","acabamentoAduela":"PET MDF BRA+BOR+REG","fechaduraMarca":"LA FONTE","fechaduraGrid":"55","fechaduraTipo":"INT","dobradicaMarca":"PAPAIZ","dobradicaMedida":"3 x 2,5","qtdeLadosAduela":"3","montantesMedida":"","montantesFolgas":"","bitsQtde":"","bitsFaces":"","camarao":false,"correr":true,"pivotante":false,"veneziana":true,"grelha":true,"bandeira":false,"chapa":false,"vidro":true,"fechaFresta":false,"kitDuplo":false,"observacao":""},
  {"bloco":"1","apto":"703","pavimento":"7","coluna":"3","comodo":"COZINHA","tipologia":"PM3F","folhaLargura":"820","folhaAltura":"2070","qtdeFolhasPorKit":"1","acabamentoPorta":"BRANCO","caracteristicaPorta":"SARRAFEADA","abertura":"DIREITA","aduelaLargura":"150","aduelaAltura":"2120","regulagem":"REG 50","acabamentoAduela":"PET MDF BRA+BOR+REG","fechaduraMarca":"LA FONTE","fechaduraGrid":"55","fechaduraTipo":"INT","dobradicaMarca":"PAPAIZ","dobradicaMedida":"3 x 2,5","qtdeLadosAduela":"3","montantesMedida":"","montantesFolgas":"","bitsQtde":"","bitsFaces":"","camarao":false,"correr":true,"pivotante":false,"veneziana":false,"grelha":true,"bandeira":false,"chapa":false,"vidro":true,"fechaFresta":false,"kitDuplo":false,"observacao":""},
  {"bloco":"1","apto":"302","pavimento":"3","coluna":"2","comodo":"LIXEIRA","tipologia":"PM7","folhaLargura":"1440","folhaAltura":"2100","qtdeFolhasPorKit":"2","acabamentoPorta":"BRANCO","caracteristicaPorta":"SARRAFEADA","abertura":"ESQUERDA P/FORA","aduelaLargura":"130","aduelaAltura":"2110","regulagem":"REG 50","acabamentoAduela":"PET MDF BRA+BOR+REG","fechaduraMarca":"LA FONTE","fechaduraGrid":"45,1","fechaduraTipo":"SÓ MAÇ.","dobradicaMarca":"LA FONTE","dobradicaMedida":"3 x 2,5","qtdeLadosAduela":"3","montantesMedida":"","montantesFolgas":"","bitsQtde":"","bitsFaces":"","camarao":false,"correr":false,"pivotante":false,"veneziana":false,"grelha":false,"bandeira":false,"chapa":false,"vidro":false,"fechaFresta":false,"kitDuplo":false,"observacao":""},
  {"bloco":"1","apto":"306","pavimento":"3","coluna":"6","comodo":"ELETRICA","tipologia":"PM12","folhaLargura":"1020","folhaAltura":"1800","qtdeFolhasPorKit":"2","acabamentoPorta":"BRANCO","caracteristicaPorta":"HONEY","abertura":"ESQUERDA P/FORA","aduelaLargura":"70","aduelaAltura":"2110","regulagem":"FIXO","acabamentoAduela":"PET MDF BRA+BOR+REG","fechaduraMarca":"LA FONTE","fechaduraGrid":"45","fechaduraTipo":"MEIO CIL.","dobradicaMarca":"LA FONTE","dobradicaMedida":"3 x 2,5","qtdeLadosAduela":"4","montantesMedida":"","montantesFolgas":"","bitsQtde":"","bitsFaces":"","camarao":false,"correr":false,"pivotante":false,"veneziana":false,"grelha":false,"bandeira":false,"chapa":false,"vidro":false,"fechaFresta":false,"kitDuplo":false,"observacao":""},
  {"bloco":"1","apto":"308","pavimento":"3","coluna":"8","comodo":"SUITE 2","tipologia":"PM2","folhaLargura":"720","folhaAltura":"2100","qtdeFolhasPorKit":"1","acabamentoPorta":"BRANCO","caracteristicaPorta":"SARRAFEADA","abertura":"DIREITA","aduelaLargura":"150","aduelaAltura":"2110","regulagem":"REG 70","acabamentoAduela":"PET MDF BRA+BOR+REG","fechaduraMarca":"LA FONTE","fechaduraGrid":"55","fechaduraTipo":"INT","dobradicaMarca":"LA FONTE","dobradicaMedida":"3 x 2,5","qtdeLadosAduela":"3","montantesMedida":"","montantesFolgas":"","bitsQtde":"","bitsFaces":"","camarao":false,"correr":false,"pivotante":false,"veneziana":false,"grelha":false,"bandeira":false,"chapa":false,"vidro":false,"fechaFresta":false,"kitDuplo":false,"observacao":""},
  {"bloco":"1","apto":"309","pavimento":"3","coluna":"9","comodo":"COZINHA","tipologia":"PM3F","folhaLargura":"820","folhaAltura":"2070","qtdeFolhasPorKit":"1","acabamentoPorta":"BRANCO","caracteristicaPorta":"SARRAFEADA","abertura":"ESQUERDA","aduelaLargura":"150","aduelaAltura":"2120","regulagem":"REG 50","acabamentoAduela":"PET MDF BRA+BOR+REG","fechaduraMarca":"LA FONTE","fechaduraGrid":"55","fechaduraTipo":"INT","dobradicaMarca":"LA FONTE","dobradicaMedida":"3 x 2,5","qtdeLadosAduela":"3","montantesMedida":"","montantesFolgas":"","bitsQtde":"","bitsFaces":"","camarao":false,"correr":false,"pivotante":false,"veneziana":false,"grelha":false,"bandeira":false,"chapa":false,"vidro":false,"fechaFresta":false,"kitDuplo":false,"observacao":""},
  {"bloco":"2","apto":"405","pavimento":"4","coluna":"5","comodo":"BANH. SOCIAL","tipologia":"PM1","folhaLargura":"620","folhaAltura":"2100","qtdeFolhasPorKit":"1","acabamentoPorta":"BRANCO","caracteristicaPorta":"HONEY","abertura":"DIREITA","aduelaLargura":"110","aduelaAltura":"2120","regulagem":"REG 50","acabamentoAduela":"PET MDF BRA+BOR+REG","fechaduraMarca":"PAPAIZ","fechaduraGrid":"55","fechaduraTipo":"WC","dobradicaMarca":"LA FONTE","dobradicaMedida":"3 x 2,5","qtdeLadosAduela":"3","montantesMedida":"","montantesFolgas":"","bitsQtde":"","bitsFaces":"","camarao":false,"correr":false,"pivotante":false,"veneziana":false,"grelha":false,"bandeira":false,"chapa":false,"vidro":false,"fechaFresta":false,"kitDuplo":false,"observacao":""},
  {"bloco":"2","apto":"501","pavimento":"5","coluna":"1","comodo":"SUITE","tipologia":"PM2","folhaLargura":"720","folhaAltura":"2100","qtdeFolhasPorKit":"1","acabamentoPorta":"BRANCO","caracteristicaPorta":"SARRAFEADA","abertura":"DIREITA","aduelaLargura":"110","aduelaAltura":"2110","regulagem":"REG 50","acabamentoAduela":"PET MDF BRA+BOR+REG","fechaduraMarca":"PAPAIZ","fechaduraGrid":"55","fechaduraTipo":"INT","dobradicaMarca":"LA FONTE","dobradicaMedida":"3 x 2,5","qtdeLadosAduela":"3","montantesMedida":"","montantesFolgas":"","bitsQtde":"","bitsFaces":"","camarao":false,"correr":false,"pivotante":false,"veneziana":false,"grelha":false,"bandeira":false,"chapa":false,"vidro":false,"fechaFresta":false,"kitDuplo":false,"observacao":""},
  {"bloco":"2","apto":"503","pavimento":"5","coluna":"3","comodo":"BANH. SUITE","tipologia":"PM1F","folhaLargura":"620","folhaAltura":"2070","qtdeFolhasPorKit":"1","acabamentoPorta":"BRANCO","caracteristicaPorta":"HONEY","abertura":"ESQUERDA","aduelaLargura":"90","aduelaAltura":"2120","regulagem":"REG 70","acabamentoAduela":"PET MDF BRA+BOR+REG","fechaduraMarca":"PAPAIZ","fechaduraGrid":"55","fechaduraTipo":"WC","dobradicaMarca":"LA FONTE","dobradicaMedida":"3 x 2,5","qtdeLadosAduela":"3","montantesMedida":"","montantesFolgas":"","bitsQtde":"","bitsFaces":"","camarao":false,"correr":false,"pivotante":false,"veneziana":false,"grelha":false,"bandeira":false,"chapa":false,"vidro":false,"fechaFresta":false,"kitDuplo":false,"observacao":""},
  {"bloco":"2","apto":"604","pavimento":"6","coluna":"4","comodo":"QUARTO","tipologia":"PM2","folhaLargura":"720","folhaAltura":"2100","qtdeFolhasPorKit":"2","acabamentoPorta":"BRANCO","caracteristicaPorta":"SARRAFEADA","abertura":"ESQUERDA","aduelaLargura":"130","aduelaAltura":"2110","regulagem":"REG 50","acabamentoAduela":"PET MDF BRA+BOR+REG","fechaduraMarca":"PAPAIZ","fechaduraGrid":"55","fechaduraTipo":"INT","dobradicaMarca":"PAPAIZ","dobradicaMedida":"3 x 2,5","qtdeLadosAduela":"3","montantesMedida":"","montantesFolgas":"","bitsQtde":"","bitsFaces":"","camarao":false,"correr":false,"pivotante":false,"veneziana":false,"grelha":false,"bandeira":false,"chapa":false,"vidro":false,"fechaFresta":false,"kitDuplo":false,"observacao":""},
  {"bloco":"2","apto":"400","pavimento":"4","coluna":"0","comodo":"SHAFT","tipologia":"PM19","folhaLargura":"1800","folhaAltura":"2100","qtdeFolhasPorKit":"3","acabamentoPorta":"BRANCO","caracteristicaPorta":"HONEY","abertura":"ESQUERDA P/FORA","aduelaLargura":"70","aduelaAltura":"2110","regulagem":"FIXO","acabamentoAduela":"PET MDF BRA+BOR+REG","fechaduraMarca":"PAPAIZ","fechaduraGrid":"45","fechaduraTipo":"MEIO CIL.","dobradicaMarca":"PAPAIZ","dobradicaMedida":"3 x 2,5","qtdeLadosAduela":"3","montantesMedida":"40","montantesFolgas":"20","bitsQtde":"","bitsFaces":"","camarao":false,"correr":false,"pivotante":false,"veneziana":false,"grelha":false,"bandeira":false,"chapa":false,"vidro":false,"fechaFresta":false,"kitDuplo":false,"observacao":""},
  {"bloco":"2","apto":"600","pavimento":"6","coluna":"0","comodo":"ESPECIAIS 1","tipologia":"PM18","folhaLargura":"2000","folhaAltura":"1800","qtdeFolhasPorKit":"4","acabamentoPorta":"BRANCO","caracteristicaPorta":"HONEY","abertura":"ESQUERDA P/FORA","aduelaLargura":"70","aduelaAltura":"2110","regulagem":"FIXO","acabamentoAduela":"PET MDF BRA+BOR+REG","fechaduraMarca":"PAPAIZ","fechaduraGrid":"45","fechaduraTipo":"MEIO CIL.","dobradicaMarca":"PAPAIZ","dobradicaMedida":"3 x 2,5","qtdeLadosAduela":"4","montantesMedida":"40","montantesFolgas":"20","bitsQtde":"","bitsFaces":"","camarao":false,"correr":false,"pivotante":false,"veneziana":false,"grelha":false,"bandeira":false,"chapa":false,"vidro":false,"fechaFresta":false,"kitDuplo":false,"observacao":""},
  {"bloco":"2","apto":"600","pavimento":"6","coluna":"0","comodo":"ESPECIAIS 2","tipologia":"PM15","folhaLargura":"1800","folhaAltura":"2100","qtdeFolhasPorKit":"4","acabamentoPorta":"BRANCO","caracteristicaPorta":"HONEY","abertura":"ESQUERDA P/FORA","aduelaLargura":"70","aduelaAltura":"2110","regulagem":"FIXO","acabamentoAduela":"PET MDF BRA+BOR+REG","fechaduraMarca":"PAPAIZ","fechaduraGrid":"55,1","fechaduraTipo":"EXT","dobradicaMarca":"PAPAIZ","dobradicaMedida":"3 x 2,5","qtdeLadosAduela":"3","montantesMedida":"40","montantesFolgas":"20","bitsQtde":"","bitsFaces":"","camarao":false,"correr":false,"pivotante":false,"veneziana":false,"grelha":false,"bandeira":true,"chapa":false,"vidro":false,"fechaFresta":false,"kitDuplo":false,"observacao":""},
  {"bloco":"2","apto":"700","pavimento":"7","coluna":"0","comodo":"ESPECIAIS 2","tipologia":"PM15","folhaLargura":"1800","folhaAltura":"2100","qtdeFolhasPorKit":"4","acabamentoPorta":"BRANCO","caracteristicaPorta":"HONEY","abertura":"ESQUERDA P/FORA","aduelaLargura":"70","aduelaAltura":"2110","regulagem":"FIXO","acabamentoAduela":"PET MDF BRA+BOR+REG","fechaduraMarca":"PAPAIZ","fechaduraGrid":"55,1","fechaduraTipo":"EXT","dobradicaMarca":"PAPAIZ","dobradicaMedida":"3 x 2,5","qtdeLadosAduela":"3","montantesMedida":"40","montantesFolgas":"20","bitsQtde":"","bitsFaces":"","camarao":false,"correr":false,"pivotante":false,"veneziana":false,"grelha":false,"bandeira":true,"chapa":false,"vidro":false,"fechaFresta":false,"kitDuplo":false,"observacao":""},
  {"bloco":"2","apto":"800","pavimento":"8","coluna":"0","comodo":"ESPECIAIS 2","tipologia":"PM15","folhaLargura":"1800","folhaAltura":"2100","qtdeFolhasPorKit":"4","acabamentoPorta":"BRANCO","caracteristicaPorta":"HONEY","abertura":"ESQUERDA P/FORA","aduelaLargura":"70","aduelaAltura":"2110","regulagem":"FIXO","acabamentoAduela":"PET MDF BRA+BOR+REG","fechaduraMarca":"PAPAIZ","fechaduraGrid":"55,1","fechaduraTipo":"EXT","dobradicaMarca":"PAPAIZ","dobradicaMedida":"3 x 2,5","qtdeLadosAduela":"3","montantesMedida":"40","montantesFolgas":"20","bitsQtde":"","bitsFaces":"","camarao":false,"correr":false,"pivotante":false,"veneziana":false,"grelha":false,"bandeira":true,"chapa":false,"vidro":false,"fechaFresta":false,"kitDuplo":false,"observacao":""},
  {"bloco":"2","apto":"900","pavimento":"9","coluna":"0","comodo":"ESPECIAIS","tipologia":"PM22","folhaLargura":"3600","folhaAltura":"2100","qtdeFolhasPorKit":"6","acabamentoPorta":"BRANCO","caracteristicaPorta":"HONEY","abertura":"ESQUERDA P/FORA","aduelaLargura":"70","aduelaAltura":"2110","regulagem":"FIXO","acabamentoAduela":"PET MDF BRA+BOR+REG","fechaduraMarca":"PAPAIZ","fechaduraGrid":"45","fechaduraTipo":"MEIO CIL.","dobradicaMarca":"PAPAIZ","dobradicaMedida":"3 x 2,5","qtdeLadosAduela":"3","montantesMedida":"80","montantesFolgas":"40","bitsQtde":"","bitsFaces":"","camarao":false,"correr":false,"pivotante":false,"veneziana":false,"grelha":false,"bandeira":false,"chapa":false,"vidro":false,"fechaFresta":false,"kitDuplo":false,"observacao":""},
  {"bloco":"2","apto":"900","pavimento":"9","coluna":"0","comodo":"ESPECIAIS","tipologia":"PM22A","folhaLargura":"3600","folhaAltura":"1800","qtdeFolhasPorKit":"6","acabamentoPorta":"BRANCO","caracteristicaPorta":"HONEY","abertura":"ESQUERDA P/FORA","aduelaLargura":"70","aduelaAltura":"2110","regulagem":"FIXO","acabamentoAduela":"PET MDF BRA+BOR+REG","fechaduraMarca":"PAPAIZ","fechaduraGrid":"45","fechaduraTipo":"MEIO CIL.","dobradicaMarca":"PAPAIZ","dobradicaMedida":"3 x 2,5","qtdeLadosAduela":"4","montantesMedida":"80","montantesFolgas":"40","bitsQtde":"","bitsFaces":"","camarao":false,"correr":false,"pivotante":false,"veneziana":false,"grelha":false,"bandeira":false,"chapa":false,"vidro":false,"fechaFresta":false,"kitDuplo":false,"observacao":""}
].map((k, i) => ({...k, id: 'k'+(i+1)}));

const newInitialKitsStr = 'const INITIAL_KITS: KitLancamento[] = \\n' + JSON.stringify(INITIAL_KITS, null, 2) + ';';
code = code.replace(/const INITIAL_KITS: KitLancamento\[\] = \[(.|\n)*?\];/, newInitialKitsStr);

fs.writeFileSync(file, code);

console.log("Updated kit representation and INITIAL_KITS");
